# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cE8ZewHPZoABpGFMOzq8gn28w_w3atqf
"""

#/content/selected_Data_set_data.csv
import pandas as pd
import matplotlib.pyplot as plt
# Read the original CSV file
original_df = pd.read_csv("Data set.csv", low_memory=False)

# Select the first 85 rows and first 2 columns
selected_data = original_df.iloc[:85, :2]

# Write the selected data to a new CSV file
selected_data.to_csv("selected_Data_set_data.csv", index=False)
print (selected_data)
# print("Data copied successfully!")
# bar chart
original_df = pd.read_csv("/content/selected_Data_set_data.csv", low_memory=False)

sums = original_df.sum()

#plotting
import matplotlib.pyplot as plt
data =  pd.read_csv("selected_Data_set_data.csv", low_memory=False)

# Assuming original_df and sums are already defined
plt.bar(data['Duration'], data['Pulse'])
plt.xlabel('Labels')  # Assuming sums.index contains appropriate labels
plt.ylabel('Duration')
plt.title('Bar Chart of Duration')
plt.show()
# Assuming original_df and sums are already defined
plt.scatter(original_df['Duration'], original_df['Pulse'])
plt.xlabel('Duration')
plt.ylabel('Pulse')
plt.title('Scatter Diagram of Duration vs Pulse')
plt.show()

# Assuming original_df and sums are already defined
plt.plot(original_df['Duration'], original_df['Pulse'])
plt.xlabel('Duration')
plt.ylabel('Pulse')
plt.title('line Diagram of Duration vs Pulse')
plt.show()

