# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YWvzBSEHgdmiZOn7fm7mqlpE4TCLEXXN
"""

import csv

# Function to count the number of rows and columns in a CSV file
def count_rows_and_columns(file_name):
    num_rows = 0
    num_columns = 0
    with open(file_name, 'r', newline='') as csvfile:
        csvreader = csv.reader(csvfile)
        for i, row in enumerate(csvreader):
            num_rows += 1
            if i == 0:  # Check only the first row to get the number of columns
                num_columns = len(row)
    return num_rows, num_columns

# Replace 'Data frame.csv' with the actual filename of your CSV file
num_rows, num_columns = count_rows_and_columns('Data set.csv')

print("Number of rows:", num_rows)
print("Number of columns:", num_columns)